# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' P
#' @param x numeric vector x coordinates
#' @param y numeric vector y coordinates
#' @export
P_d <- function(x, y) {
    .Call(`_rearcut_P_d`, x, y)
}

#' Polygon triangulation
#'
#' Constrained polygon triangulation by ear cut algorithm,
#' also known as ear clipping.
#' @param x numeric vector x coordinates
#' @param y numeric vector y coordinates
#' @export
#' @examples
#' X <- c(0, 0, 0.75, 1, 0.5, 0.8, 0.69, 0)
#' Y <- c(0, 1, 1, 0.8, 0.7, 0.6, 0, 0)
#' ind <- rearcut(X, Y)  ## should be longer than 0 :)
#' if (length(ind) < 3) {
#'  ## this is rgl's solution, it's not necessarily deterministic
#'  ind <- c(8L, 2L, 1L, 8L, 5L, 2L, 8L, 7L, 5L, 5L, 3L, 2L, 5L,
#'               4L, 3L, 7L, 6L, 5L) - 1
#' }
#' plot(X, Y)
#' apply(matrix(ind, nrow = 3), 2, function(x) polygon(cbind(X, Y)[x + 1, ]))
rearcut <- function(x, y) {
    .Call(`_rearcut_rearcut`, x, y)
}

